name: ruhrkultur
description: A new Flutter project.

version: 0.4.93-alpha+0.4.93

environment:
  sdk: ">=2.19.0 <3.22.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  get:
  get_storage:

  flutter_screenutil: ^5.9.3
  loading_overlay_pro: ^2.1.1
  dio: ^5.4.3+1
  awesome_drawer_bar: ^1.2.0
  responsive_grid_list: ^1.4.0
  http: ^1.2.1
  cached_network_image: ^3.3.1
  audio_service: ^0.18.13
  just_audio: ^0.9.38
  get_it: ^7.7.0
  about: ^2.1.3
  package_info_plus: ^8.0.0
  audio_video_progress_bar: ^2.0.3
  flutter_archive: ^6.0.3
  rive: ^0.13.8
  flutter_svg: ^2.0.10+1
  awesome_dialog: ^3.2.1
  gap: ^3.0.1
  responsive_framework: ^1.4.0
  flutter_modular: ^6.3.4
  redacted: ^1.0.11
  #Video
  video_player: ^2.8.7
  cached_video_player_plus: ^3.0.2
  #Permission
  permission_handler: ^11.3.1
  #Location
  geolocator: ^12.0.0
  #File System
  path_provider: ^2.1.3
  #Audio Player
  audioplayers: ^6.0.0
  #QR Code
  barcode_scan2: ^4.3.3
  #Game engine
  flame: ^1.18.0
  #Map
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  # #to make native splash screen
  # # 1) change path image_path
  # # 2) run commened -> flutter pub run flutter_native_splash:create
  #   flutter_native_splash: ^2.1.1
  # flutter_native_splash:
  #   background_image: assets/image/splash_background.png # choose one color or background
  #   color: "#ffffff"
  #   image: assets/icons/icon.png

  # # to change icon
  # # 1) change path image_path
  # # 2) run commened -> flutter pub run flutter_launcher_icons:main
  #   flutter_launcher_icons: ^0.9.2
  # flutter_icons:
  #   android: true
  #   ios: true
  #   remove_alpha_ios: true
  #   image_path: "assets/icons/icon.png"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/image/
    - assets/animation/
    - assets/svg/
  uses-material-design: true
