// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5XPS0nv03849Xxv4pGE-QTjSc1gFnD98',
    appId: '1:852027341174:web:3cbeb5f95ee1993f072257',
    messagingSenderId: '852027341174',
    projectId: 'ruhurkultur',
    authDomain: 'ruhurkultur.firebaseapp.com',
    databaseURL: 'https://ruhurkultur-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ruhurkultur.appspot.com',
    measurementId: 'G-873QB46FVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCGzhKy_IHaxcUpjnaAAkvlkiRREuzGSg',
    appId: '1:852027341174:android:028b2a643ee532ca072257',
    messagingSenderId: '852027341174',
    projectId: 'ruhurkultur',
    databaseURL: 'https://ruhurkultur-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ruhurkultur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxeAnMkN9NvKVgJ-i8A_Yd3tio3-7Vie4',
    appId: '1:852027341174:ios:7ba0b24e6e5e37f5072257',
    messagingSenderId: '852027341174',
    projectId: 'ruhurkultur',
    databaseURL: 'https://ruhurkultur-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ruhurkultur.appspot.com',
    androidClientId: '852027341174-h6d3vckshkthfs4pg4rfi4tfaj3ks6uj.apps.googleusercontent.com',
    iosClientId: '852027341174-dlvab444kstnruveffq6fnie2sthanae.apps.googleusercontent.com',
    iosBundleId: 'com.filmprojekt1.ruhrkulturerlebnisapp.reka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxeAnMkN9NvKVgJ-i8A_Yd3tio3-7Vie4',
    appId: '1:852027341174:ios:7ba0b24e6e5e37f5072257',
    messagingSenderId: '852027341174',
    projectId: 'ruhurkultur',
    databaseURL: 'https://ruhurkultur-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ruhurkultur.appspot.com',
    androidClientId: '852027341174-h6d3vckshkthfs4pg4rfi4tfaj3ks6uj.apps.googleusercontent.com',
    iosClientId: '852027341174-dlvab444kstnruveffq6fnie2sthanae.apps.googleusercontent.com',
    iosBundleId: 'com.filmprojekt1.ruhrkulturerlebnisapp.reka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5XPS0nv03849Xxv4pGE-QTjSc1gFnD98',
    appId: '1:852027341174:web:f0cc747d5873e3cd072257',
    messagingSenderId: '852027341174',
    projectId: 'ruhurkultur',
    authDomain: 'ruhurkultur.firebaseapp.com',
    databaseURL: 'https://ruhurkultur-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ruhurkultur.appspot.com',
    measurementId: 'G-51FT9B9S4J',
  );
}
